name: SWISSMARKiOS

options:
  bundleIdPrefix: com.swissmark
  deploymentTarget:
    iOS: "17.0"

targets:
  SWISSMARKiOS:
    type: application
    platform: iOS

    sources:
      - SWISSMARKiOS

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swissmark.ios
      SWIFT_VERSION: 5.0
      INFOPLIST_FILE: SWISSMARKiOS/Info.plist
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_EMIT_LOC_STRINGS: YES

    scheme:
      gatherCoverageData: false
